### ISSUE TITLE
Code of Conduct needs a email ID.

### ISSUE THREAD

**Issue by vishwasnavadak** [lanyard/lanyard#6]
I had placed a placeholder for email in the code of conduct in #2 . We might have to place an email ID there 😅

**Comment by hnprashanth** [comment]
Can't see any email id mentioned in Code of conduct

**Comment by vishwasnavadak** [comment]
> Can't see any email id mentioned in Code of conduct

Markdown is skipping it since I mentioned the placeholder between `< >`. It is line 58 of CODE_OF_CONDUCT.md. Visible when viewed raw or in edit mode. 

![image](https://user-images.githubusercontent.com/13111030/63209702-076a1980-c102-11e9-9a02-4a0ee63b9abd.png)

**Comment by hnprashanth** [comment]
Updated
